# 🟢 Node base image
FROM node:20

# Set working directory
WORKDIR /app

# Copy package.json + lock
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy rest of the app
COPY frontend/ .

RUN rm -rf node_modules dist && npm ci

RUN npm run build

RUN npm install -g serve

# Expose Vite dev server port
EXPOSE 8000

# Start dev server
CMD ["serve", "-s", "dist", "-l", "8000"]

